### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.tencent.bugly.symtabtool.proguard.fe

### ISSUE THREAD

**Issue by sandin** [JalenChen/symtabfileuploader#4]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:uploadReleaseSymtabFile'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.tencent.bugly.symtabtool.proguard.fe
	at com.tencent.bugly.symtabtool.proguard.du.e(Bugly:5086)
	at com.tencent.bugly.symtabtool.proguard.du.a(Bugly:8106)
	at com.tencent.bugly.symtabtool.proguard.du.a(Bugly:10382)
	at com.tencent.bugly.symtabtool.common.upload.SymtabFileUploader.a(Bugly:197)
	at com.tencent.bugly.symtabtool.common.upload.SymtabFileUploader.uploadSymtabFile(Bugly:254)
	at com.tencent.bugly.symtabtool.common.upload.SymtabFileUploader$uploadSymtabFile.call(Unknown Source)
	at com.tencent.bugly.gradle.BuglyPlugin.uploadSymbolFile(BuglyPlugin.groovy:257)
	at com.tencent.bugly.gradle.BuglyPlugin.this$2$uploadSymbolFile(BuglyPlugin.groovy)
	at com.tencent.bugly.gradle.BuglyPlugin$_processFiles_closure1.doCall(BuglyPlugin.groovy:307)
	at com.tencent.bugly.gradle.BuglyPlugin.processFiles(BuglyPlugin.groovy:296)
	at com.tencent.bugly.gradle.BuglyPlugin.this$2$processFiles(BuglyPlugin.groovy)
	at com.tencent.bugly.gradle.BuglyPlugin$_createUploadTask_closure12.doCall(BuglyPlugin.groovy:617)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more

**Comment by msdx** [comment]
I meet the same error.

**Comment by msdx** [comment]
symtabfileuploader: 2.0.7
log:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:uploadDevelopReleaseSymtabFile'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.ExceptionInInitializerError
        at com.tencent.bugly.symtabtool.proguard.fe.<clinit>(Bugly:144)
        at com.tencent.bugly.symtabtool.proguard.du.e(Bugly:5086)
        at com.tencent.bugly.symtabtool.proguard.du.a(Bugly:8106)
        at com.tencent.bugly.symtabtool.proguard.du.a(Bugly:10382)
        at com.tencent.bugly.symtabtool.common.upload.SymtabFileUploader.a(Bugly:197)
        at com.tencent.bugly.symtabtool.common.upload.SymtabFileUploader.uploadSymtabFile(Bugly:254)
        at com.tencent.bugly.symtabtool.common.upload.SymtabFileUploader$uploadSymtabFile.call(Unknown Source)
        at com.tencent.bugly.gradle.BuglyPlugin.uploadSymbolFile(BuglyPlugin.groovy:258)
        at com.tencent.bugly.gradle.BuglyPlugin$_processFiles_closure1.doCall(BuglyPlugin.groovy:314)
        at com.tencent.bugly.gradle.BuglyPlugin.processFiles(BuglyPlugin.groovy:302)
        at com.tencent.bugly.gradle.BuglyPlugin$_createUploadTask_closure12.doCall(BuglyPlugin.groovy:637)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:596)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:577)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:90)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:86)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more
Caused by: com.tencent.bugly.symtabtool.proguard.x: The chosen LogFactory implementation does not extend LogFactory. Please check your configuration. (Caused by java.lang.UnsupportedOperationException: Operation [getClassLoader] is not supported in jcl-over-slf4j. See also http://www.slf4j.org/codes.html#unsupported_operation_in_jcl_over_slf4j)
        at com.tencent.bugly.symtabtool.proguard.y.a(Bugly:1154)
        at com.tencent.bugly.symtabtool.proguard.aa.run(Bugly:960)
        at com.tencent.bugly.symtabtool.proguard.y.a(Bugly:957)
        at com.tencent.bugly.symtabtool.proguard.y.getFactory(Bugly:624)
        at com.tencent.bugly.symtabtool.proguard.y.getLog(Bugly:655)
        at com.tencent.bugly.symtabtool.proguard.fa.<init>(Bugly:60)
        at com.tencent.bugly.symtabtool.proguard.fb.<init>(Bugly:43)
        at com.tencent.bugly.symtabtool.proguard.fb.<clinit>(Bugly:45)
        ... 37 more
Caused by: java.lang.UnsupportedOperationException: Operation [getClassLoader] is not supported in jcl-over-slf4j. See also http://www.slf4j.org/codes.html#unsupported_operation_in_jcl_over_slf4j
        at org.apache.commons.logging.LogFactory.getClassLoader(LogFactory.java:378)
        at org.apache.commons.logging.impl.LogFactoryImpl.getClassLoader(LogFactoryImpl.java:392)
        at org.apache.commons.logging.impl.LogFactoryImpl.initDiagnostics(LogFactoryImpl.java:420)
        at org.apache.commons.logging.impl.LogFactoryImpl.<init>(LogFactoryImpl.java:87)
        at com.tencent.bugly.symtabtool.proguard.y.a(Bugly:1047)
        ... 44 more
```

**Comment by LouisShark** [comment]
do you solve this problem ? I hava the same issue @msdx

**Comment by msdx** [comment]
@LouisShark I have forgotten.
